project:
  type: website
  output-dir: docs
website:
  title: "COSy"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - publicaciones.qmd
      - software.qmd
      - datasets.qmd
      - videos.qmd
      - about.qmd
format:
  html:
    theme: lux
    toc: true
execute:
  freeze: auto